view/frontend/templates/product/viewed.phtml
"Unable to parse JSON-LD tag. Malformed JSON found..." reported in chrome developer console whenever a product is viewed that has a comma in the price  (Products over $1k). There's prob a better way to approach this aside from `number_format` but just added a quick hotfix.
=> Malformed JSON error when price has a comma in it (Products over $1k)

Api/ReclaimInterface.php, Model/Reclaim.php
We are currently using an invalid return type. https://devdocs.magento.com/guides/v2.3/extension-dev-guide/service-contracts/service-to-web-service.html
Valid scalar types include: mixed (or anyType), bool (or boolean), str (or string), integer (or int), float, and double.
=> fix invalid return type

Api/ReclaimInterface.php, Model/Reclaim.php, composer.json, etc/module.xml, etc/webapi.xml, module.xml
It appears we don't get customers who subscriber as a guest as the hooks don't fire.  this is to expose 2 api endpoints to be able to query this data.  
1. for historical sync by id's (batching)
2. for periodic date pull (since param)
Endpoints:
```
@param mixed $start
@param mixed $until
@param mixed $store_id
```
/V1/klaviyo/reclaim/customers/subscriptions/periodic
Ex
```
rest/V1/klaviyo/reclaim/customers/subscriptions/periodic?start=2019-04-25%20:00:00&until=2019-04-25%2018:00:00:00
```
```
@param mixed $start_id	   
@param mixed $end_id	     
@param mixed $store_id
```
/V1/klaviyo/reclaim/customers/subscriptions/historical
```
http://magento2.local:8888/rest/V1/klaviyo/reclaim/customers/subscriptions/historical?start_id=1&end_id=10
```
=> subscriber api endpoint

Api/ReclaimInterface.php, Controller/Checkout/Email.php, Helper/Data.php, Model/Reclaim.php, composer.json, etc/adminhtml/system.xml, etc/module.xml
creates:
If someone has a custom media url route, they can specify it here, it will then allow the products api endpoint to utilize that custom url
also, making sure it's a valid url 
handles issues #32 #33
=> Media URLS & Fix Schema & fix checkout email 

Api/ReclaimInterface.php, Controller/Checkout/Email.php, Helper/Data.php, Model/Reclaim.php, composer.json, etc/adminhtml/system.xml, etc/module.xml
creates:
If someone has a custom media url route, they can specify it here, it will then allow the products api endpoint to utilize that custom url
also, making sure it's a valid url 
handles issues #32 #33
=> revert revert Media URLS & Fix Schema & fix checkout email

Model/Reclaim.php, composer.json, etc/module.xml
A little context here: A customer's M2 sync was failing due to memory limits, and I initially asked him to increase his PHP memory limit. He said he didn't want to do that, and instead came up with another suggestion. He ended up making the change in this PR on his fork, and reported that the sync started working once he switched to his version of the extension. Some context here:
https://webkul.com/blog/optimizing-magento-magento2-part-1/
=> Changes getCount to getSize

view/frontend/web/js/view/checkout/email.js
When we disabled Klaviyo extension in the admin - we started getting following JS error on checkout page while editing email address field:
I investigated this issue and found that there is no check if Klaviyo is available. 
In addition to that - Klaviyo still saves email to quote, even when module is not enabled.
My PR checks if Klaviyo global variable (`window._learnq`) is not available - do not try to track or send requests about saving email to quote.
=> Fix JS error on checkout page when Klaviyo module disabled

Helper/Data.php, Setup/UpgradeData.php, composer.json, etc/module.xml
Added helper methods and UpgradeData.php file to encrypt private API key when upgrading from versions lower than 1.1.7
=> Private API Key Hashing Fix

Setup/InstallData.php
Magento core handles log file creation, and creating/chmodding the log file in this install script is not only incorrect but can cause integration test failure
=> Unnecessary logger file creation

Controller/Checkout/Cart.php
If the URL has parameters other than the quote ID, allow those parameters to persist through the cart redirect. If there are no other parameters in the URL, redirect normally.
=> Allow URL parameters to persist through cart redirect

view/frontend/web/js/view/checkout/email.js
jQuery UI is never used in the email.js, but including it on the **define**, and it starts loading the all UI library (jQuery UI with all Widgets).
As a result, email.js will be run just after all libs with included in **define**.
Also, it creates a performance issue for the checkout page.
=> Remove jQuery UI to improve performance

etc/config.xml
Setting CSP settings in an extension not maintained by a merchant can cause un-intended issues. Leaving the CSP settings up to the merchant is a better approach.
=> Removed CSP setting

CHANGELOG.md, Helper/Data.php
Tested and confirmed consent is sent with the subscription request:
And consent is recorded:
Also confirmed consent is not sent when using the members endpoint:
=> Record email consent when using subscribe endpoint

CHANGELOG.md
The links in the changelog are not correct.
❌ Release [2.1.0](https://github.com/klaviyo/magento2-klaviyo/blob/master/CHANGELOG.md#210---2021-03-22) don't have  any link
❌ Release [2.0.0 ](https://github.com/klaviyo/magento2-klaviyo/blob/master/CHANGELOG.md#200---2021-01-11) goes to https://github.com/klaviyo/magento2-klaviyo/compare/2.0.0...2.1.0
My PR fixes it, so it will become to this:
✔ Release [2.1.0](https://github.com/klaviyo/magento2-klaviyo/blob/master/CHANGELOG.md#210---2021-03-22) goes to https://github.com/klaviyo/magento2-klaviyo/compare/2.0.0...2.1.0
✔ Release [2.0.0 ](https://github.com/klaviyo/magento2-klaviyo/blob/master/CHANGELOG.md#200---2021-01-11) goes to https://github.com/klaviyo/magento2-klaviyo/compare/1.2.4...2.0.0
=> Fix incorrect links in changelog

CHANGELOG.md, Observer/ProductDeleteBefore.php, Setup/UpgradeSchema.php, composer.json, etc/module.xml
Fixes bug to use store_ids instead of website_ids for delete product webhook.
Also fixes bug where we were looking for versions greater than 2.0.0 in the UpgradeSchema.
=> Use store ids in the ProductDeleteBefore Observer

Helper/ScopeSetting.php
Right now, we don't have the ability to retrieve info about Klaviyo from a different store. This is really useful, for instance, in the cron jobs, when we can process multiple accounts.
=> Add ability to retrieve config values for specified store id

CHANGELOG.md, Helper/Data.php
Use case - we would like to send some events to Klaviyo in the cron job for a specific store (different stores synced to different Klaviyo accounts).
Right now, we can't specify to which Klavityo account we should send this event.
This PR brings an ability to send the event to a specific Klaviyo account (specified on store level).
=> Add an ability to pass the Store ID during track event

etc/adminhtml/events.xml, etc/events.xml, etc/frontend/events.xml
Pre-history:  we have a custom Checkout extension that has built-in functionality for subscribing to the newsletter. This subscription happening on the same request as "place order". This request usually happening in the `webapi_rest` area. As a result, in Magento, we have subscribers, but in Klaviyo, this information isn't getting sent, so **we're losing subscribers**.
My Pull Request changing handling [all possible areas](https://devdocs.magento.com/guides/v2.4/architecture/archi_perspectives/components/modules/mod_and_areas.html), including `webapi_rest`, `webapi_soap`, `graphql` and `crontab`,  as well as existing `frontend` and `adminhtml`.
=> Handle newsletter subscriptions in all areas

CHANGELOG.md, Model/Quote/QuoteIdMask.php, Plugin/Api/CartSearchRepository.php, composer.json, etc/module.xml
This pertains to github issue [here](https://github.com/klaviyo/magento2-klaviyo/issues/133) and implements some of the logic [here](https://github.com/magento/magento2/pull/33324) as its still unreleased code.  
It addresses the bug where if a quote with a coupon has `trigger_recollect = 1` then any api calls to retrieve the quote will hang forever. Instead of relying on the magento libraries to retrieve the masked quote id, we implement code to retrieve it ourselves from the DB
=> adding code changes to handle infinite loop issue

CHANGELOG.md, view/frontend/templates/checkout/cart.phtml, view/frontend/web/js/view/checkout/email.js
Implements change suggested in #94 and also implements this URL builder on cart.phtml template
Also replaces reference to deprecated _learnq functionality (`_learnq.identify.$email`) with an equivalent (`_learnq.isIdentified()`)
=> Use Magento URL builder to build URLs

CHANGELOG.md, Plugin/CheckoutLayoutPlugin.php, composer.json, etc/module.xml
Problem Statement:
Usually When an user adds a product to the shopping cart and proceeds with the checkout process.  The checkbox for SMS consent would appear just below the field for Phone Number as illustrated below:
If the user happens to be logged in and has default address set, user is not given the opportunity to enter address details like we saw for the first example.  Instead you see a uneditable box with the address info as illustrated below:
Solution:
Expose just between the default address and where user has to select the shipping method the redundant field for Phone Number with SMS consent checkbox underneath:
=> Fix to Expose SMS Consent For Logged In Users with Default Address Set

Model/Events.php, Model/KlaviyoCollection.php, Model/Products.php, Model/ResourceModel/Events.php, Model/ResourceModel/Events/Collection.php, Model/ResourceModel/Products.php, Model/ResourceModel/Products/Collection.php, Model/ResourceModel/Syncs.php, Model/ResourceModel/Syncs/Collection.php, Model/Syncs.php, Setup/SchemaInterface.php, etc/db_schema.xml
Starting 2.3, Magento decided to deprecate InstallSchema/UpgradeSchema, InstallData/UpgradeData scripts to using a db_schema.xml file and call it [declarative schema](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/). 
If any of our customers are using a version older than 2.3.4, they can't upgrade M2 extensions to post 3.0.5, so we decided to go ahead with implementing this approach to add new tables. 
Magento suggests creating Models for each table to carry out CRUD operations on table. So each of the three tables have their own Model,ResourceModel and Collection classes.
The structure of such Models should be as follows:
```
extension_root
`-- Models
|-- New_table.php
`-- ResourceModel
|-- New_table.php
`-- New_table
`-- Collection.php
```
=> Message queues db setup

Cron/EventsTopic.php, Cron/KlSyncs.php, Helper/Data.php, Observer/SalesQuoteProductAddAfter.php, Observer/SalesQuoteSaveAfter.php, etc/cron_groups.xml, etc/crontab.xml, etc/db_schema.xml, etc/events.xml
2 Observers are being used to record the Added to Cart events to the kl_events table
1. SalesQuoteProductAddAfter >> This is triggered by Magento when a product is added to a quote (cart) by a user and this captures multiple scenarios:
a. Product added from it's page
b. Product added from wishlist
c. Re-Order of product
At this point, the SalesQuoteProductAddAfter observer will construct the payload for the event and creates a session variable
The SalesQuoteSaveAfter event is triggered when the Quote is saved and this enables us to get the QuoteId and send over with the payload to be able to reconstruct the cart later. This observer will read from the checkout session variable from the previous observer, attach the quote Id and then write to the kl_event table
The cron jobs require the …
=> Message queues -  Added to Cart observers and Cron logic

CHANGELOG.md, composer.json, etc/config.xml, etc/module.xml
https://klaviyo.tpondemand.com/entity/91329-update-sms-cac-default-template-language
Updating the SMS consent at checkout default language to say:
**By checking this box and entering your phone number above, you consent to receive marketing text messages (such as [promotion codes] and [cart reminders]) from [company name] at the number provided, including messages sent by autodialer. Consent is not a condition of any purchase. Message and data rates may apply. Message frequency varies. You can unsubscribe at any time by replying STOP or clicking the unsubscribe link (where available) in one of our messages. View our Privacy Policy [link] and Terms of Service [link].
=> 202111 update sms consent lang

Controller/Checkout/Cart.php, Cron/EventsTopic.php, Cron/KlSyncs.php, Observer/SalesQuoteProductAddAfter.php, Observer/SalesQuoteSaveAfter.php, etc/csp_whitelist.xml, view/frontend/web/js/customer.js
This PR fixes a few things: 
MaskedQuoteId is not generated for quotes associated with Logged in users. In such a situation, we would send a null back with the ATC payload, with no way to rebuild cart for these users. 
[TP](https://klaviyo.tpondemand.com/entity/99989-rebuild-carts-for-logged-in-customers)
There was a lot of noise in the console caused by csp policies not whitelising the klaviyo scripts
[TP](https://klaviyo.tpondemand.com/entity/101804-whiteslist-klaviyo-domains-in-magento-2)
Logged in users were not correctly being cookied as the customerData was being generated after script. It will now wait for this to be generated before trying to cookie the user.
=> Rebuild cart for Logged-in users, whitelist klaviyo scripts, identify logged in users correctly

CHANGELOG.md, Helper/Data.php, composer.json, etc/module.xml
Addressing two existing bugs with ATC: 
- Updated the `klaviyoTrackEvent` method to make a POST request instead of a GET to account for larger payloads. Using POST should allow for payloads up to 1 MB. 
- Fixed bug due to an undefined property `observerAtcPayload` that was raising errors.
=> 202203 tp107056 atc updates

composer.json
currently Magento customers on versions < 2.4.x that install v 4.0.0 of extension will experience errors like this in their website appearing for their users:
`main.min.js:2 TypeError: customerData.getInitCustomerData is not a function`
the fix ensures that customers on versions < 2.4.x will not be able to install the latest extension and should instead revert to v 3.0.11 of the klaviyo extension.
=> adding require for customer library specific to v 2.4+

.github/CODEOWNERS, CHANGELOG.md, Helper/Webhook.php, Observer/SalesQuoteProductAddAfter.php, composer.json, etc/module.xml
This update encapsulates changes that were in the develop branch - as they were all simple 1-2 line changes I created a fresh branch to avoid the git issues we were having. I will be closing the develop branch after the next release. 
- Moving webhooks to the async tier (Austin)
- Adding require for customer library specific to v 2.4+ (Jad)
- Remove product description from ATC payload (Claire)
- CODEOWNERS update (Claire)
- Version bump and changelog update (Claire)
=> 202204 release 4.0.3

CHANGELOG.md, composer.json
Removing the version restriction for the customers module, this is causing some release issues and we are going to go forward with releasing the other changes until we can prioritize debugging the version restriction.
=> removed module requirement

CHANGELOG.md, composer.json, etc/module.xml
Reverts the version bump back down to 4.0.2 and moves the changes up for the next release under Unreleased in the changelog to reduce any confusion.
=> Release stalled - reverted version bump and updated changelog

CHANGELOG.md, view/frontend/templates/checkout/cart.phtml
The base URL needs to be set, otherwise you will generate a relative URL which will 404 on any URL that has a path with more than 1 level deep (ie:  /checkout/cart)
=> Fix 404 AJAX Request

CHANGELOG.md, Observer/NewsletterSubscribeObserver.php
https://klaviyo.tpondemand.com/entity/131521-m2-extension-not-syncing-newsletter-subscribers
Bug Description: when a user registered for an account on the account creation page the subscription wasn't properly being added to Klaviyo because `subscriber->hasDataChanges` was evaluating to false for new users. This change adjusts the logic to additionally check to see if the subscriber is new. We should now subscribe/unsubscribe registered users to Klaviyo lists when the subscription is either updated on the /customer/account/ page or if they checked the box on the /customer/account/create/ page.
=> Fixed newsletter signup on account creation page

CHANGELOG.md, composer.json, etc/module.xml
Version bump for extension release: 
moves all unreleased items under version 4.0.5, updates links in changelog, updates composer.json and etc/module.xml
=> Version bumps for 4.0.5

CHANGELOG.md, Controller/Checkout/Reload.php
This PR replaces the backend context with the frontend one. Since this controller is used on frontend, it doesn't make any sense to create classes needed for backend, e.g. backend session which is part of this context.
Basically, it just improves speed of this controller and reduces session locks on checkout 
1.
=> Do not load not needed backend classes

CHANGELOG.md, view/frontend/layout/default.xml
Give the `Klaviyo\Reclaim\Block\Initialize` block a name giving theme developers the option of referencing the block and moving it elsewhere.
=> Allow developers to move the Klaviyo\Reclaim\Block\Initialize block

CHANGELOG.md, Cron/EventsTopic.php, Cron/KlSyncs.php, Model/KlaviyoCollection.php, Observer/SalesQuoteSaveAfter.php
This PR encompasses several improvements for the added to cart event. Namely it enforces the payload size, and doesn't allow for rows with truncated payload to be committed to the database. 
Previously, truncated Added to Cart payloads would raise unhandled exceptions when processing in both `Cron/EventsTopic.php` and `Cron/KlSyncs.php`, which in turn would prevent the processing of the remaining rows. The unhandled exceptions also prevented the rows that were able to move over to the kl_sync table from being marked as MOVED, leading to repetitive processing and continuous retries. This PR adds exception handling which will log the exception and mark any rows that raise exceptions during processing as FAILED. The cleanup crons have been adjusted to additionally delete FAILED rows from …
=> ATC bug fixes, updated cleanup crons, enforce payload size

CHANGELOG.md, composer.json, etc/crontab.xml, etc/module.xml
Bug fix for cron job - incorrect method was being called after the 4.0.7 refactors which affected the cleanup cron for the kl_events table. 
1. On a local account, made sure cleanup cron ran as expected and that MOVED or FAILED rows were removed from the kl_events table
=> Bug fix add correct method to cron

CHANGELOG.md, etc/config.xml
Updates default sms consent language 
1.
=> 202212 update default sms lang

CHANGELOG.md, view/frontend/templates/product/viewed.phtml, view/frontend/web/js/customer.js, view/frontend/web/js/view/checkout/email.js
Updated the legacy `_learnq` js object to the new `klaviyo` js object.
1. Validated the `klaviyo` object is available when the klaviyo.js script is installed.
=> TP156258: Switch from _learnq to klaviyo object in javascript

CHANGELOG.md, Observer/NewsletterSubscribeObserver.php
This adds Magento 2 as the source when customers subscribe to the newsletter.
Logging $source properties on Klaviyo profiles is necessary to track where contacts are originating from and understanding their various user journeys, similar to understanding traffic source patterns in Google Analytics.
Source ID used was supplied by Klaviyo Support and can be referenced here: https://help.klaviyo.com/hc/en-us/articles/1260804673530-Source-Value-Reference
1. Subscribe to the newsletter.
2. The subscriber's profile should have Magento 2 specified as the source
=> Subscriber source

CHANGELOG.md, Observer/NewsletterSubscribeObserver.php
This PR fixes a bug where customers that hadn't confirmed their email for their Site account were getting unsubscribed in Klaviyo. This was happening because we weren't accounting for the other two order statuses in our observer file - as a result every subscription update where the customer wasn't explicitly subscribed resulted in them getting unsubscribed. 
Tested the following scenerios: 
1. Create a new account for a site that has account confirmation required enabled and opt in to the newsletter. The Klaviyo newsletter settings are set to use the Klaviyo Double Opt-in. 
- Verify that the profile has not been created on Klaviyo yet
- Confirm account via the email
- Verify that I've received the Klaviyo DOI email and once that is confirmed that the profile has been added to the list
2. …
=> 202302 tp165376

CHANGELOG.md, etc/extension_attributes.xml
PR preventing Klaviyo to block checkout from working - error with method getKlSmsConsent() and getklEmailConsent() already issued on #191 
Magento 2.4.5
PHP 8.1
Enable the module, then go at "Stores > Configuration > Klaviyo > Consent at Checkout" section and flag "Subscribe contacts to email marketing at checkout" to "Yes" or/and  flag "Subscribe contacts to SMS marketing at checkout" to "Yes". 
Save the configurations, clean config cache.
After that go on checkout as guest and try complete an order.
Before this fix, magento checkout will block you sending a 500 error on rest/default/V1/guest-carts/shipping-information endpoint and showing the following message (if your magento is in developer mode, webapi report error on production instead):
<< Property "KlEmailConsent" does not have …
=> Fix shipping information update on checkout for klEmailConsent and klSmsConsent fields

.changelogger.yml, CHANGELOG.md, Observer/NewsletterSubscribeObserver.php, composer.dev.json
In Magento versions <2.4.3 `isStatusChanged` doesn't evaluate to true for net new subscriptions made through any magento newsletter forms. This prevents new subscriptions from syncing to Klaviyo. This PR adds in a check for `isObjectNew` to be backwards compatible with old m2 versions. 
1. Tested locally on a 2.4.2 instance
=> 202307 update subscribe conditional2

CHANGELOG.md, Helper/Data.php
Bug fix for #277 
Uses `getMessage()` instead of array indexing.
1. Tested on local magento 2 with a bad private API key. Verified that the admin newsletter page renders successfully
=> updates the exception handling for getKlaviyoLists

.gitignore, .idea/codeStyles/codeStyleConfig.xml, CHANGELOG.md, KlaviyoV3Sdk/KlaviyoV3Api.php
V3 lists api only returns 10 lists per page. In order to fully populate the Newsletter configuration dropdown menu we need to paginate to fetch all lists for an account.
1. local setup, tested with an account with 155 lists and with an account with 4 lists. 155 had a few seconds of latency due to the synchronous requests
=> Paginate lists for newsletter setup

etc/acl.xml, etc/adminhtml/system.xml
This pull request creates the ACL that's raised in this issue https://github.com/klaviyo/magento2-klaviyo/issues/160
It creates permissions for each klaviyo configuration area. 
1. php bin/magento cache:clean
2. Log into the admin panel
3. Go to system -> User Roles
4. Check whether the new klaviyo roles appear (control+f klaviyo)
=> Create ACL for Klaviyo config settings

.distignore, .github/workflows/continuous_deployment.yml, .gitignore
Adds a step to the CD workflow to create a zip archive while excluding files that don't need to be released through a `.distignore` file.
1. Forked the repo and made these updates to test distignore, zip and adding artifact to release. See attachced zip file for example of output.
[klaviyo_reclaim-4.1.0.zip](https://github.com/klaviyo/magento2-klaviyo/files/13654136/klaviyo_reclaim-4.1.0.zip)
=> Add create archive step to CD workflow

KlaviyoV3Sdk/KlaviyoV3Api.php
This PR fixes behavior for when `curl_exec` returns something that is not explicitly false but evaluates to false (ex: `null`). This will prevent successful responses from retrying and follows the recommendation here: https://www.php.net/manual/en/function.curl-exec.php#refsect1-function.curl-exec-returnvalues
1.
=> update response handling for false

CHANGELOG.md, view/frontend/web/js/customer.js
Fixes a bug where we don't correctly handle the Promise returned by `klaviyo.isIdentified()`. Was preventing us from identifying customers after account registration or login. 
1. Tested that I'm correctly identified in Klaviyo after registering a new account
2. Tested that I'm correctly identified in Klaviyo after logging into an account.
=> Add promise handling to isIdentified() call

CHANGELOG.md, Helper/Data.php, KlaviyoV3Sdk/Exception/KlaviyoApiException.php, KlaviyoV3Sdk/Exception/KlaviyoAuthenticationException.php, KlaviyoV3Sdk/Exception/KlaviyoException.php, KlaviyoV3Sdk/Exception/KlaviyoRateLimitException.php, KlaviyoV3Sdk/Exception/KlaviyoResourceNotFoundException.php, KlaviyoV3Sdk/Exception/index.php, KlaviyoV3Sdk/KlaviyoV3Api.php, Model/Config/Source/ListOptions.php, Observer/UserProfileNewsletterSubscribeObserver.php, composer.json, etc/module.xml, view/frontend/templates/product/viewed.phtml, view/frontend/web/js/customer.js, view/frontend/web/js/view/checkout/email.js
Adds a patch for extension version 3.0.4 to switch it over to Klaviyo's V3 APIs ahead of the V1/V2 API retirement. 
**This patch only updates the extension to use Klaviyo's v3 APIs. No other bug fixes were made as part of this work.**
1. Tested on a 2.3.3 store locally
=> V3 API patch for 3.0.4

CHANGELOG.md, Cron/KlSyncs.php, Observer/SalesQuoteProductAddAfter.php
Previously we synced the configurable product image path instead of the simple product that was added to the cart. This PR updates that behavior to use the simple product image if applicable, and fall back on the configurable product if we cannot find an image on the simple product. 
It also adds 2 new event fields for Added to cart: StoreId and AddedSimpleProductId. These are stored at the top level and can be used for additional filtration or use in catalog tags in email templates. 
1. Tested simple products, bundles, groups, and configurable products. Made sure the correct fields were syncing to klaviyo. Validated that the behavior for bundles and grouped products was unchanged. Verified that simple product information is syncing correctly for simple product and configurable product …
=> Updates Added to Cart event to use simple product images where applicable

CHANGELOG.md, KlaviyoV3Sdk/KlaviyoV3Api.php
Hey, you've formatted the properties incorrectly, in the profile object, in properties is a child of data / attributes - see https://jsonformatter.org/fa628e for reference which was taken from the API example on Klaviyo
Fixes bug with sending custom data on a profile to Klaviyo events API
This is an event we sync to Klaviyo that updates a customer profile. This field is no longer updating the contact. I've checked the API documentation and I have found this bug. 
{"data":{"type":"event","attributes":{"properties":{"$value":null},"time":"2024-02-06T13:46:34","value":null,"metric":{"data":{"type":"metric","attributes":{"name":"Customer Sync","service":"magentotwo"}}},"profile":{"data":{"type":"profile","attributes":{"email":"bcedd554123b00cff993@redacted.com","first_name":"Leila","last_name" …
=> Fix customer custom properties KlaviyoV3Api.php

CHANGELOG.md, KlaviyoV3Sdk/KlaviyoV3Api.php
Fixes a bug where we weren't url encoding emails before requesting the `api/profiles/` endpoint. For emails containing special characters this was resulting in misses on the search and the following request to create the new profile would fail because it does already exist. 
1. Selected to **not** use Klaviyo's opt-in settings in the extension settings. Then filled out the M2 footer form with an email that already existed in Klaviyo, made sure it was properly added to list. 
2. Tested the same as above but with a new email that didn't exist in Klaviyo. 
=> Adds urlencode to email before search request

Block/Catalog/Product/ViewedProduct.php, CHANGELOG.md, Cron/KlSyncs.php, Helper/ScopeSetting.php, Observer/SalesQuoteSaveAfter.php
Will allow for filtering within Klaviyo on StoreID. This matches the field that we sync on app-side events (Placed Order, Ordered Product, etc). 
1. Tested events using local magento instance on 2.4.6
=> Adds StoreID field to Added to Cart and Viewed Product events

Block/Catalog/Product/ViewedProduct.php, CHANGELOG.md, Cron/KlSyncs.php, Helper/ScopeSetting.php, Observer/SalesQuoteSaveAfter.php
Reverts klaviyo/magento2-klaviyo#303
got too late to the jump on this one - too many accounts are on 4.1.4 using `StoreId`. We are gonna leave it in to avoid introducing breaking changes
=> Revert "Adds StoreID field to Added to Cart and Viewed Product events"

composer.dev.json, composer.dev.lock
Updating dev dependencies to take advantage of recent features/changes. Addresses [ECOS-4387](https://klaviyo.atlassian.net/browse/ECOS-4387)
Both [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) and [PHPCodesniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) have new maintainers.
PHPCodesniffer is actively releasing new versions - we're updating to take advantage of the newest features. The recently forked repo under current maintenance is available under the same packagist entry squizlabs/php_codesniffer 🙌
PHPCompatibility hasn't released a new version but the `develop` branch is getting new php 8.x sniffs and the branch is available. Let's use it to get access to those 8.x sniffs.
1. Made incompatible change locally - caught by pre-commit
**NOTE:** …
=> Update phpcompatibility and codesniffer

CHANGELOG.md, view/frontend/web/js/view/checkout/email.js
addresses #306 by adding the correct handling for the promise returned from klaviyo.isIdentified(). This fixes a bug where we weren't correctly identifying profiles from the checkout page.
1. tested new behavior on a local magento site, valildated the klaviyo profile was correctly created. 
=> updates email.js to correctly handle the klaviyo object promise

Block/Catalog/Product/ViewedProduct.php, CHANGELOG.md, Helper/Data.php, KlaviyoV3Sdk/KlaviyoV3Api.php, Observer/SalesQuoteSaveAfter.php, Test/.env.example, Test/e2e/api/viewed-product.spec.js, Test/e2e/locators/admin.js, Test/e2e/locators/storefront.js
Adds external_catalog_id and integration_key to the two events that are shipped from the magento 2 extension: Viewed Product, and Added to Cart. 
1. Tested locally on a multi-storefront account, making sure the correct catalog ids were used. 
2. Going to run through the playwright tests
=> Adds external_catalog_id and integration_key to M2 events.

CHANGELOG.md, Plugin/Api/AddProductRelationships.php, composer.dev.json, composer.json, etc/extension_attributes.xml, etc/module.xml, etc/webapi_rest/di.xml
This PR adds an extension attribute to the Products API data interface, both individual and bulk requests.
This uses the built-in Configurable resource's method `getParentIdsByChild`. Will return an empty array if the product is not associated with a parent.
1. Update extension and make request to `/index.php/rest/V1/products` or `/index.php/rest/V1/products/:sku` route.
2. Example response:
```
"extension_attributes": {
"website_ids": [
1
],
"category_links": [
...
],
"stock_item": {
...
},
"kl_parent_ids": [
2
]
}
```
=> Add parent ids to Product extension attributes

.changelogger.yml, .github/workflows/continuous_integration.yml, composer.magento-coding-standard.dev.json, composer.magento-coding-standard.dev.lock, view/frontend/templates/analytics/initialize.phtml, view/frontend/templates/product/viewed.phtml
Fixes Magento Coding Standard failures in phtml template files.
Adds a blocking CI check that runs phpcs with the Magento Coding Standard (see screenshot below for sample failure). Note this only alerts on severity=10 which is the same as the Magento Marketplace automated technical review. Had to add a separate composer file for this particular CI check because it's incompatible with the `dev-develop` branch of the PHPCompatibliity tool which is the only way we can get the ongoing maintenance for php 8 compatibility checks.
[Failure](https://github.com/klaviyo/magento2-klaviyo/actions/runs/17443713199/job/49532782384?pr=341) 
1.
=> add phpcs check with Magento Coding Standard to CI

CHANGELOG.md, composer.dev.json, composer.json, composer.magento-coding-standard.dev.json, etc/module.xml, view/frontend/templates/product/viewed.phtml
Version 4.4.0 included escapeJS calls to satisfy the M2 codesniffer. these caused issues for the klaviyo.js calls, preventing Viewed Product events from syncing successfully. 
1. Tested changes locally and validated that viewed product events were synced successfully.
=> Skip unescaped errors from sniffer
