Helper/Data.php, composer.json, view/frontend/templates/analytics/initialize.phtml, view/frontend/templates/product/viewed.phtml
Getting real image of product at all times. 
Performance improvement: altering DOM while html parsing is in progress is bad practice. 
Removing strict version, version is simply git tag in github.
Added source as optional parameter for subscription.
=> Improvements

README.md
=> Propose fix a typo

Block/Catalog/Product/ViewedProduct.php, view/frontend/templates/product/viewed.phtml
=> Code refactoring / load default product image

Api/ReclaimInterface.php, Controller/Checkout/Email.php, Helper/Data.php, Model/Reclaim.php, composer.json, etc/adminhtml/system.xml, etc/module.xml
Reverts klaviyo/magento2-klaviyo#34
=> Revert "Media URLS & Fix Schema & fix checkout email "

Plugin/Customer/Model/CustomerData.php
Fixes error:
Uncaught Error: Call to undefined method Magento\Customer\Helper\Session\CurrentCustomer::getLastname()
=> Fixes error undefined method getLastname

etc/config.xml
* Let Magento know to decrypt the password before creating a new user
=> update namespace used in config.xml

Helper/Data.php
Switch to Klaviyo Lists v2 API endpoint 
This endpoint triggers "Unsubscribed from %ListName%" event
=> Fix reporting Unsubscribe from List event

etc/webapi.xml
Make all API routes available only when you have needed permissions
=> Add corresponding permissions to Web API resources

.gitignore, Helper/Data.php, composer.json, etc/module.xml
* found a couple of typos that have been here for a very long time
* fixed namespacing issue I missed during refactoring (unit tests will help prevent that in the future!)
=> small updates and bugfix for Data.php

Block/Catalog/Product/ViewedProduct.php
=> include price in 'Viewed Item' payload

etc/config.xml, etc/csp_whitelist.xml
=> Add Content Security Policy (CSP)

Helper/Data.php, Helper/Logger.php, Logger/Handler.php
Small adjustments to pass M2 Marketplace automated test suite
=> Compatibility updates for Magento Marketplace test suite

etc/config.xml
=> report_only = true

Model/Reclaim.php, Test/Data/SampleExtension.php, composer.json, etc/config.xml, etc/module.xml
- Removes unused variable and DI from Reclaim.php
- Update CSP to be in report-only mode
- Bump version to 1.2.3
=> Remove unused variable, CSP report-only mode

.gitignore, CHANGELOG.md, README.md
Updates readme w/ how to make a PR and semantic versioning.  Adds changelog
=> update readme for changes

CHANGELOG.md, Helper/Data.php, Model/Config/Source/ListOptions.php
We currently use v1 api in the fetching of lists, if there are too many lists then not all lists will be shown inside the UI
=> use list v2 api for newsletter lists

CHANGELOG.md, etc/csp_whitelist.xml
add api value to csp whitelist
=> Add api to whitelist

Api/ReclaimInterface.php, CHANGELOG.md, Helper/Data.php, Helper/ScopeSetting.php, Helper/Webhook.php, Model/Reclaim.php, Observer/ProductDeleteAfter.php, Observer/ProductDeleteBefore.php, composer.json, etc/adminhtml/events.xml, etc/adminhtml/system.xml, etc/config.xml, etc/webapi.xml
This does the first pass for starting to add webhooks.
The first one will be the ProductDeleteBefore as well as adding a webhook secret for validation
=> Product Delete Webhook & API

CHANGELOG.md, Controller/Checkout/Cart.php, composer.json, etc/module.xml
=> Typo in cart rebuild

CHANGELOG.md, Plugin/Api/CartSearchRepository.php, composer.json, etc/module.xml
to support Magento 2 customers on 2.3.0 to 2.3.3
=> required changes to use SearchResults instead of CartSearchResults

CHANGELOG.md, Model/Reclaim.php
Right trim trailing slash from Custom Media Url setting from Klaviyo Extension
=> 202107 rtrim custom media url

CHANGELOG.md, Observer/NewsletterSubscribeObserver.php, composer.json, etc/module.xml
Fixing issue where anonymous users (not registered accounts) try to subscribe to newsletter and do not get synched to the associated list in Klaviyo
=> newsletter fix

Cron/EventsTopic.php, etc/crontab.xml
There were some capitilization errors which were causing code to be generated in the wrong place.
=> Uncaught capitilization fixes

CHANGELOG.md, Plugin/CheckoutLayoutPlugin.php, composer.json, etc/config.xml, etc/module.xml, view/frontend/templates/checkout/cart.phtml, view/frontend/web/js/view/checkout/email.js
More of a merge master into develop, I had to test this on the test store to ensure nothing breaks
=> 202112 test develop with master

CHANGELOG.md, Observer/NewsletterSubscribeObserver.php, composer.json, etc/module.xml
fixes issue affecting customers who subscribe to an embedded M2 footer form and see an error message
=> adding fix and updating version

CHANGELOG.md, Helper/Data.php, composer.json, etc/module.xml
Updating the remote develop branch to incorporate the 4.0.2 changes
=> 202204 update remote develop

composer.json
Updating the composer.json file for a wider version range
=> Update composer.json module-customer version

CHANGELOG.md, composer.json, etc/csp_whitelist.xml, etc/db_schema.xml, etc/module.xml
https://klaviyo.tpondemand.com/restui/board.aspx?#page=bug/122309
https://klaviyo.tpondemand.com/entity/122237-m2-244-customers-hitting-deprecated-functionality
=> tp122237 tp122309

CHANGELOG.md, Observer/SalesQuoteProductAddAfter.php
Addresses: https://github.com/klaviyo/magento2-klaviyo/issues/201
=> added conditional around stripslashes call

Block/Catalog/Product/ViewedProduct.php, CHANGELOG.md
This is a bug fix addressing #209 
1. Tested viewed product functionality on all product types using PHP 8.1
=> 202210 tp146253 fix grouped product price

CHANGELOG.md, composer.json, etc/module.xml
Version bump for release 4.0.7
1.
=> Version bump for 4.0.7

CHANGELOG.md, composer.json, etc/module.xml
Bumps version for 4.0.9 release
1.
=> version bump for 4.0.9 release

composer.dev.json, composer.dev.lock, makefile
=> Add composer dev for local development

.changelogger.yml, .github/pull_request_template.md, .github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml, CHANGELOG.md, README.md
###
- Add CI/CD Workflows
- Implements pre-commit checks
1.
=> TP159720: Adds CI/CD Workflows

CHANGELOG.md, composer.json, etc/module.xml
=> version bump for 4.0.10

.github/pre-commit/action-validator.sh, .github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml, .github/workflows/stable_patch_deployment.yml, .pre-commit-config.yaml
Updates this repos GitHub Action workflows to follow the latest release strategy. Also introduces action-validator to pre-commit, to aid in preventing bad workflow deployments.
1. Ran against action validator.
=> TP167877: Update release strategy

.github/workflows/continuous_deployment.yml, .github/workflows/stable_patch_deployment.yml
This will mark M2 releases as prereleases, per the m2 specific release pattern.
1.
=> Mark as pre-release for m2

CHANGELOG.md, Model/Reclaim.php
Title says it all, see ticket: https://klaviyo.tpondemand.com/entity/170341-magento-2-customers-historical-sync
1.
=> fixes historical sync zero index bug

CHANGELOG.md, Controller/Checkout/Email.php, Helper/Data.php, Helper/ScopeSetting.php, Model/Config/Source/ListOptions.php, Model/Reclaim.php, Observer/KlaviyoOAuthObserver.php, Plugin/CheckoutLayoutPlugin.php
Addresses PHP 8.2 incompatabilities - in 8.2 they deprecated dynamic properties: https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties 
1.
=> 202304 tp170170

CHANGELOG.md, composer.json, etc/module.xml
=> version bump

CHANGELOG.md, view/frontend/layout/checkout_index_index.xml
With this adaption, it is possible to reference the block, so it can be adapted to custom needs.
=> Add name to checkout analytics block

.gitignore, CHANGELOG.md, KlaviyoV3Sdk/KlaviyoV3Api.php, composer.dev.json, composer.json, etc/module.xml
Increments version to trigger CD workflow and release new version of extension.
Waiting on addition of two community PRs before releasing:
- #276
- #264 
1.
=> Release 4.1.1

CHANGELOG.md, Cron/KlSyncs.php, Helper/Data.php, KlaviyoV3Sdk/KlaviyoV3Api.php, Observer/SalesQuoteSaveAfter.php, composer.dev.json, composer.json, etc/module.xml
This PR addresses several bugs from 4.1.0 release which added support for Klaviyo's V3 APIs. 
* Fixes issues with store-scoped requests. If you scope each store to a different Klaviyo account we will now correctly retrieve the correct private API key and sync the events. 
* Fixes response handling for Added to Cart requests - previously our APIs returned 0/1 for failure/success. Now we return json with more information about the errors (if applicable). This updates our handling to accept the new response schema and correctly marks successful rows as such. 
* Fixes logging to log out a much more useful error message on retries, adds handling for 401s
* Updates Added to Cart observers to check for the private api key instead of the public key. 
* Fixes a bug w/ directly adding a profile to …
=> Bug fixes for v3 api release

.gitignore, CHANGELOG.md, Helper/Data.php, KlaviyoV3Sdk/Exception/KlaviyoApiException.php, KlaviyoV3Sdk/Exception/KlaviyoAuthenticationException.php, KlaviyoV3Sdk/Exception/KlaviyoException.php, KlaviyoV3Sdk/Exception/KlaviyoRateLimitException.php, KlaviyoV3Sdk/Exception/KlaviyoResourceNotFoundException.php, KlaviyoV3Sdk/Exception/index.php, KlaviyoV3Sdk/KlaviyoV3Api.php, Model/Config/Source/ListOptions.php, Observer/PrivateApiKeyObserver.php, Observer/UserProfileNewsletterSubscribeObserver.php, composer.json, etc/module.xml, view/frontend/templates/product/viewed.phtml, view/frontend/web/js/customer.js, view/frontend/web/js/view/checkout/email.js
This PR adds a patch for version 2.2.0 of the extension to support Klaviyo's v3 APIs. 
**This patch only updates the extension to use Klaviyo's v3 APIs. No other bug fixes were made as part of this work as Klaviyo no longer actively maintains extensions linked for Magento 2 <2.3**
1. Tested locally on a 2.2.11 store. 
=> v3 API patch 2.2.0

KlaviyoV3Sdk/KlaviyoV3Api.php
Fixes issue with custom properties. Although `track` isn't called from the klaviyo module code, we are including it in the patch release so folks that have customized their m2 module version to include custom track requests can easily migrate these over to the new APIs. 
1.
=> adds fix for custom props on track requests

CHANGELOG.md, Helper/Data.php, composer.dev.json, composer.json, etc/module.xml
=> Removes unnecessary $response var binding.

Block/Catalog/Product/ViewedProduct.php, CHANGELOG.md, Helper/Logger.php, Helper/ScopeSetting.php, composer.dev.json, composer.json, etc/module.xml, view/frontend/templates/analytics/initialize.phtml
* Update the Magento 2 klaviyo.js url to the new format
* bumps version
* small fix for Area code is already set bug (#166, #296)
1. tested on local site - made sure that form appears and the url is formatted correctly. 
=> M2 Version 4.2.0 release

CHANGELOG.md, Model/Reclaim.php
=> 202503 ecos 10127

Block/Catalog/Product/ViewedProduct.php, CHANGELOG.md, KlaviyoV3Sdk/KlaviyoV3Api.php, composer.dev.json, composer.json, etc/module.xml
Bumps the version to 4.3.0, updates the changelog.
1.
=> Bumps version for 4.3.0 release

CHANGELOG.md, Controller/Checkout/Email.php
Replaces backend context with frontend context as this is a frontend controller.
Fixes #347 - similar to https://github.com/klaviyo/magento2-klaviyo/pull/214
1.
=> Update Email controller constructor
